In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('http://10.237.200.3/loyalty_sub_info2.dsv', encoding = 'utf8')

/Users/academy_intern/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (7,14,15,17,27,28,38,45,52) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [28]:
data

,COUNTRY,OPCO_NAME,OPCO_BUSINESS_TYPE,UCID,MSISDN,SUBSCRIBER_TYPE,CUSTOMER_TYPE,B2B_TYPE,CONS_TYPE,TARIFF_TYPE,...,BAL_DAYS_NEGATIVE,BAL_TIMES_LESS_5,BAL_TIMES_NEGATIVE,BAL_LAST_DAY_PERIOD,DEL_CVS_SCORE,MSISDN_LOY,REG_DATE,SMILE_BALANCE,VALID_ID,SEX
0,South Africa,SA,Mobile,8.927000e+18,3238415789,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,3238415789,13-AUG-2018 00:00:00,5198.5200,Y,M
1,South Africa,SA,Mobile,8.927000e+18,3649564471,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,3649564471,13-MAY-2018 00:00:00,52.0000,Y,F
2,South Africa,SA,Mobile,8.927000e+18,3375328257,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,3375328257,26-AUG-2018 00:00:00,105.6300,Y,F
3,South Africa,SA,Mobile,8.927000e+18,2435751696,P,CONSUMER,NaN,VL,MTNZone,...,NaN,NaN,NaN,NaN,NaN,2435751696,21-AUG-2018 00:00:00,35.0000,N,F
4,South Africa,SA,Mobile,8.927000e+18,2001140033,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,2001140033,16-MAY-2018 00:00:00,87.0000,N,F
5,South Africa,SA,Mobile,8.927000e+18,129566128,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,129566128,21-JUL-2018 00:00:00,370.9900,N,M
6,South Africa,SA,Mobile,8.927000e+18,307715829,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,307715829,11-JUN-2018 00:00:00,357.6200,Y,M
7,South Africa,SA,Mobile,8.927000e+18,1048096802,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,1048096802,11-SEP-2018 00:00:00,18.0000,Y,F
8,South Africa,SA,Mobile,8.927000e+18,2133106569,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,2133106569,29-JUL-2018 00:00:00,432.4800,Y,M
9,South Africa,SA,Mobile,8.927000e+18,217822465,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,217822465,27-MAY-2018 00:00:00,1478.7500,Y,M
10,South Africa,SA,Mobile,8.927000e+18,859869161,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,859869161,27-AUG-2018 00:00:00,770.9600,N,NaN
11,South Africa,SA,Mobile,8.927000e+18,1764578376,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,1764578376,07-JUN-2018 00:00:00,412.9000,N,NaN
12,South Africa,SA,Mobile,8.927000e+18,3424802567,P,CONSUMER,NaN,VL,Pep Club MTN Base,...,NaN,NaN,NaN,NaN,NaN,3424802567,18-MAY-2018 00:00:00,164.1500,Y,M
13,South Africa,SA,Mobile,8.927000e+18,2773177449,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,2773177449,02-SEP-2018 00:00:00,92.9900,Y,F
14,South Africa,SA,Mobile,8.927000e+18,826273850,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,826273850,10-AUG-2018 00:00:00,104.5000,Y,F
15,South Africa,SA,Mobile,8.927000e+18,2438080069,P,CONSUMER,NaN,VL,Pep Club MTN Base,...,NaN,NaN,NaN,NaN,NaN,2438080069,27-JUN-2018 00:00:00,213.4400,Y,M
16,South Africa,SA,Mobile,8.927000e+18,2090202775,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,2090202775,12-JUN-2018 00:00:00,120.5300,Y,F
17,South Africa,SA,Mobile,8.927000e+18,646682235,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,646682235,16-JUL-2018 00:00:00,89.0000,Y,F
18,South Africa,SA,Mobile,8.927000e+18,2589977216,P,CONSUMER,NaN,VL,Pep Club MTN Base,...,NaN,NaN,NaN,NaN,NaN,2589977216,21-APR-2018 00:00:00,93.0000,Y,M
19,South Africa,SA,Mobile,8.927000e+18,625346006,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,625346006,23-AUG-2018 00:00:00,25.8800,Y,F
20,South Africa,SA,Mobile,8.927000e+18,47994510,P,CONSUMER,NaN,VL,Pep Club MTN Base,...,NaN,NaN,NaN,NaN,NaN,47994510,19-APR-2018 00:00:00,225.9600,Y,M
21,South Africa,SA,Mobile,8.927000e+18,632851323,P,CONSUMER,NaN,VL,MTNZone,...,NaN,NaN,NaN,NaN,NaN,632851323,25-MAY-2018 00:00:00,116.0000,N,M
22,South Africa,SA,Mobile,8.927000e+18,1278558702,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,1278558702,18-AUG-2018 00:00:00,109.5100,Y,F
23,South Africa,SA,Mobile,8.927000e+18,33538367,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,33538367,10-JUN-2018 00:00:00,102.0000,Y,M
24,South Africa,SA,Mobile,8.927000e+18,2425873437,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,2425873437,16-SEP-2018 00:00:00,7.3100,Y,F
25,South Africa,SA,Mobile,8.927000e+18,662528718,P,CONSUMER,NaN,VL,Pep Club MTN Base,...,NaN,NaN,NaN,NaN,NaN,662528718,23-JUN-2018 00:00:00,311.0600,Y,M
26,South Africa,SA,Mobile,8.927000e+18,13186512,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,13186512,09-APR-2018 00:00:00,50.4900,N,F
27,South Africa,SA,Mobile,8.927000e+18,680378312,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,680378312,31-AUG-2018 00:00:00,32.0000,Y,F
28,South Africa,SA,Mobile,8.927000e+18,3470597370,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,3470597370,02-JUL-2018 00:00:00,103.0000,Y,F
29,South Africa,SA,Mobile,8.927000e+18,756992522,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,756992522,20-AUG-2018 00:00:00,31.0000,N,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1863369,South Africa,SA,Mobile,8.927000e+18,3070080235,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,3070080235,22-AUG-2018 00:00:00,30.3100,N,F
1863370,South Africa,SA,Mobile,8.927000e+18,4065114199,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,4065114199,10-DEC-2017 00:00:00,428.9800,Y,F
1863371,South Africa,SA,Mobile,8.927000e+18,871598970,P,CONSUMER,NaN,VL,MTN Base,...,NaN,NaN,NaN,NaN,NaN,871598970,11-JUL-2018 00:00:00,37.0000,N,F
1863372,South Africa,SA,Mobile,8.927000e+18,3701370339,P,CONSUMER,NaN,VL,MTNZone,...,NaN,NaN,NaN,NaN,NaN,3701370339,12-MAR-2009 00:00:00,292.9299,Y,F
1863373,South Africa,SA,Mobile,8.927000e+18,1338129640,P,CONSUMER,NaN,VL,MTNZone,...,NaN,NaN,NaN,NaN,NaN,1338129640,20-JUN-2018 00:00:00,8.5400,Y,M
1863374,South Africa,SA,Mobile,8.927000e+18,3612633017,P,CONSUMER,NaN,VL,MTN Talk Free,...,NaN,NaN,NaN,NaN,NaN,3612633017,18-DEC-2016 00:00:00,94.1800,N,NaN
1863375,South Africa,SA,Mobile,8.927000e+18,4095979379,P,CONSUMER,NaN,VL,MTNZone,...,NaN,NaN,NaN,NaN,NaN,4095979379,17-JAN-2017 00:00:00,75.9900,Y,M
1863376,South Africa,SA,Mobile,8.927000e+18,1758679628,P,CONSUMER,NaN,VL,MTNZone,...,NaN,NaN,NaN,NaN,NaN,1758679628,27-OCT-2016 00:00:00,225.0100,Y,F
1863377,South Africa,SA,Mobile,8.927000e+18,275431437,P,CONSUMER,NaN,VL,MTNZone,...,NaN,NaN,NaN,NaN,NaN,275431437,12-MAR-2009 00:00:00,137.2414,Y,F
1863378,South Africa,SA,Mobile,8.927000e+18,635899392,P,CONSUMER,NaN,VL,MTNZone,...,NaN,NaN,NaN,NaN,NaN,635899392,13-OCT-2015 00:00:00,11.9000,Y,M
1863379,South Africa,SA,Mobile,8.927000e+18,2959818051,P,CONSUMER,NaN,VL,Pep Club MTN Base,...,NaN,NaN,NaN,NaN,NaN,2959818051,27-APR-2018 00:00:00,20.7100,Y,M
1863380,South Africa,SA,Mobile,8.927000e+18,2240534161,P,CONSUMER,NaN,VL,MTNZone,...,NaN,NaN,NaN,NaN,NaN,2240534161,10-DEC-2012 00:00:00,19.0550,Y,F
1863381,South Africa,SA,Mobile,8.927000e+18,420441886,P,CONSUMER,NaN,VL,UNKNOWN,...,NaN,NaN,NaN,NaN,NaN,420441886,05-SEP-2018 00:00:00,0.0000,Y,F
1863382,South Africa,SA,Mobile,8.927000e+18,3576783071,P,CONSUMER,NaN,VL,Pep Club MTN Base,...,NaN,NaN,NaN,NaN,NaN,3576783071,29-AUG-2018 00:00:00,84.5000,Y,M
1863383,South Africa,SA,Mobile,8.927000e+18,3017320959,P,CONSUMER,NaN,VL,MTNZone,...,NaN,NaN,NaN,NaN,NaN,3017320959,12-MAR-2009 00:00:00,68.0483,Y,M
1863384,South Africa,SA,Mobile,8.927000e+18,2273923421,P,CONSUMER,NaN,VL,PAYG Data4Keeps,...,NaN,NaN,NaN,NaN,NaN,2273923421,07-JUL-2009 00:00:00,58.1449,Y,M
1863385,South Africa,SA,Mobile,8.927000e+18,3062316118,P,CONSUMER,NaN,VL,MTNZone,...,NaN,NaN,NaN,NaN,NaN,3062316118,22-AUG-2017 00:00:00,17.0200,Y,M
1863386,South Africa,SA,Mobile,8.927000e+18,2676362831,P,CONSUMER,NaN,VL,MTN Pay Per Second,...,NaN,NaN,NaN,NaN,NaN,2676362831,08-AUG-2016 00:00:00,6.7300,Y,F
1863387,South Africa,SA,Mobile,8.927000e+18,2577356292,P,CONSUMER,NaN,VL,MTNZone,...,NaN,NaN,NaN,NaN,NaN,2577356292,12-JAN-2018 00:00:00,11.0000,N,F
1863388,South Africa,SA,Mobile,8.927000e+18,15531415,P,CONSUMER,NaN,VL,MTN Talk Free,...,NaN,NaN,NaN,NaN,NaN,15531415,22-FEB-2011 00:00:00,142.2058,Y,M
1863389,South Africa,SA,Mobile,8.927000e+18,3444653542,P,CONSUMER,NaN,VL,MTNZone,...,NaN,NaN,NaN,NaN,NaN,3444653542,12-AUG-2017 00:00:00,739.1100,Y,M
1863390,South Africa,SA,Mobile,8.927000e+18,924334173,P,CONSUMER,NaN,VL,MTNZone,...,NaN,NaN,NaN,NaN,NaN,924334173,10-JUN-2017 00:00:00,155.1600,N,NaN
1863391,South Africa,SA,Mobile,8.927000e+18,1496296258,P,CONSUMER,NaN,VL,MTN Pay Per Second,...,NaN,NaN,NaN,NaN,NaN,1496296258,08-MAR-2009 00:00:00,140.8245,Y,F
1863392,South Africa,SA,Mobile,8.927000e+18,2363302119,P,CONSUMER,NaN,VL,MTN Pay Per Second,...,NaN,NaN,NaN,NaN,NaN,2363302119,21-MAY-2010 00:00:00,276.7958,Y,F
1863393,South Africa,SA,Mobile,8.927000e+18,267815970,P,CONSUMER,NaN,VL,MTNZone,...,NaN,NaN,NaN,NaN,NaN,267815970,20-DEC-2017 00:00:00,7.6700,Y,F
1863394,South Africa,SA,Mobile,8.927000e+18,4202297545,P,CONSUMER,NaN,VL,MTNZone,...,NaN,NaN,NaN,NaN,NaN,4202297545,10-NOV-2011 00:00:00,196.4852,Y,F
1863395,South Africa,SA,Mobile,8.927000e+18,2617202048,P,CONSUMER,NaN,VL,MTNZone,...,NaN,NaN,NaN,NaN,NaN,2617202048,21-JAN-2011 00:00:00,136.8561,Y,M
1863396,South Africa,SA,Mobile,8.927000e+18,2858722271,P,CONSUMER,NaN,VL,MTNZone,...,NaN,NaN,NaN,NaN,NaN,2858722271,10-MAR-2009 00:00:00,265.1596,Y,F
1863397,South Africa,SA,Mobile,8.927000e+18,3236206174,P,CONSUMER,NaN,VL,MTNZone,...,NaN,NaN,NaN,NaN,NaN,3236206174,29-SEP-2010 00:00:00,58.0730,Y,M
1863398,South Africa,SA,Mobile,8.927000e+18,1406118983,P,CONSUMER,NaN,VL,MTNZone,...,NaN,NaN,NaN,NaN,NaN,1406118983,11-SEP-2016 00:00:00,129.5000,N,M

In [7]:
data['FIRST_USAGE_DATE'] = pd.to_datetime(data['FIRST_USAGE_DATE'])

In [8]:
data_1 = data.loc[data['LOYALTY_POINTS_REDEEMED']>0]

In [9]:
data_2 = data_1.loc[data_1['FIRST_USAGE_DATE'] >= pd.to_datetime('2018-08-01 00:00:00')]

In [10]:
cons = data_2.loc[data_2['CUSTOMER_TYPE'] == 'CONSUMER']

In [11]:
cons['CUSTOMER_TYPE'].count()

7098

In [12]:
cons['LOYALTY_POINTS_BALANCE'].mean()

39.79705019746091

In [13]:
u = cons.nlargest(5, 'LOYALTY_POINTS_REDEEMED')

In [14]:
u['LOYALTY_POINTS_REDEEMED'].mean()

14880.0

In [15]:
u[['HS_MAKE','SEX','LOYALTY_POINTS_REDEEMED','SMILE_BALANCE','LOYALTY_POINTS_BALANCE']]

,HS_MAKE,SEX,LOYALTY_POINTS_REDEEMED,SMILE_BALANCE,LOYALTY_POINTS_BALANCE
24019,Samsung,M,33900.0,1125.0000,1105.0000
1199965,Samsung,F,15000.0,3025.0000,19.8300
812734,Huawei,M,10100.0,29910.8553,29890.8553
834984,Apple,NaN,8500.0,48.3030,378.3030
1292850,Vodafone,F,6900.0,199.4500,148.0000

In [16]:
cons[['HS_MAKE','SEX','REV_VOICE_ONNET','CONS_TYPE','REV_VOICE_OFFNET','B2B_TYPE','CUSTOMER_TYPE','TARIFF_TYPE','LOYALTY_POINTS_REDEEMED','SMILE_BALANCE','LOYALTY_POINTS_BALANCE']]

,HS_MAKE,SEX,REV_VOICE_ONNET,CONS_TYPE,REV_VOICE_OFFNET,B2B_TYPE,CUSTOMER_TYPE,TARIFF_TYPE,LOYALTY_POINTS_REDEEMED,SMILE_BALANCE,LOYALTY_POINTS_BALANCE
118,TECNO,NaN,-1500.0,VL,0.0,NaN,CONSUMER,MTN Base,60.0,3.00,14.00
251,Lenovo,F,-300.0,VL,0.0,NaN,CONSUMER,MTN Base,20.0,25.00,5.00
284,HURRICANE,M,0.0,VL,0.0,NaN,CONSUMER,MTNZone,20.0,20.99,19.00
383,itel,M,0.0,VL,0.0,NaN,CONSUMER,MTN Base,20.0,30.00,10.00
740,Nokia,M,0.0,VL,0.0,NaN,CONSUMER,MTN Base,40.0,15.00,15.00
1079,itel,M,0.0,VL,0.0,NaN,CONSUMER,MTN Base,20.0,17.00,10.00
1189,Samsung,NaN,0.0,VL,0.0,NaN,CONSUMER,Pep Club MTN Base,20.0,27.00,7.00
1991,Nokia,M,0.0,VL,0.0,NaN,CONSUMER,MTN Base,20.0,24.00,4.00
2086,STYLO,F,0.0,VL,0.0,NaN,CONSUMER,MTN Base,20.0,30.00,10.00
2152,Nokia,F,0.0,VL,0.0,NaN,CONSUMER,MTN Base,20.0,53.00,33.00
2306,MINT,F,0.0,VL,0.0,NaN,CONSUMER,MTNZone,20.0,7.00,7.00
2313,Alcatel,M,0.0,VL,0.0,NaN,CONSUMER,MTN Base,20.0,24.00,4.00
2345,Vodafone,F,0.0,VL,0.0,NaN,CONSUMER,MTN Base,20.0,42.00,22.00
2447,Samsung,M,0.0,VL,0.0,NaN,CONSUMER,MTN Base,20.0,45.00,25.00
2740,NaN,F,0.0,VL,0.0,NaN,CONSUMER,MTNZone,20.0,12.53,28.00
2759,Alcatel,F,0.0,VL,0.0,NaN,CONSUMER,MTN Base,20.0,42.00,22.00
2922,MOBICEL,NaN,0.0,VL,0.0,NaN,CONSUMER,MTN Base,20.0,5.00,25.00
3006,Samsung,F,0.0,VL,0.0,NaN,CONSUMER,MTN Base,20.0,32.00,12.00
3025,Vodacom,F,0.0,VL,0.0,NaN,CONSUMER,MTN Base,40.0,35.00,15.00
3044,MOBICEL,F,0.0,VL,0.0,NaN,CONSUMER,MTN Base,20.0,36.00,16.00
3053,AG,F,0.0,VL,0.0,NaN,CONSUMER,MTN Base,20.0,14.00,14.00
3068,STYLO,M,0.0,VL,0.0,NaN,CONSUMER,MTNZone,20.0,49.00,29.00
3088,Nokia,F,0.0,VL,0.0,NaN,CONSUMER,MTN Base,20.0,42.99,13.00
3133,itel,F,0.0,VL,0.0,NaN,CONSUMER,MTNZone,20.0,10.00,10.00
3306,MINT,F,0.0,VL,0.0,NaN,CONSUMER,MTN Base,20.0,16.00,6.00
3318,VOLT MOBILE,M,0.0,VL,0.0,NaN,CONSUMER,MTN Base,20.0,10.00,10.00
3337,Vodacom,M,0.0,VL,0.0,NaN,CONSUMER,MTN Base,1000.0,47.00,27.00
3589,HURRICANE,F,0.0,VL,0.0,NaN,CONSUMER,MTN Base,20.0,10.00,10.00
3625,Nokia,F,0.0,VL,0.0,NaN,CONSUMER,MTN Base,20.0,5.00,5.00
3651,STYLO,M,0.0,VL,0.0,NaN,CONSUMER,MTN Base,20.0,11.00,31.00
...,...,...,...,...,...,...,...,...,...,...,...
1858499,Vodacom,F,2584.0,VL,431.0,NaN,CONSUMER,Pep Club MTN Base,40.0,7.10,7.00
1859027,K-LITE,F,1593.0,VL,31.0,NaN,CONSUMER,MTNZone,100.0,3.11,41.11
1859094,NOKIA,M,1930.0,VL,2877.0,NaN,CONSUMER,MTN Pay Per Second,200.0,144.48,108.27
1859368,Nokia,M,2392.0,L,639.0,NaN,CONSUMER,MTN Base,20.0,9.60,38.83
1859665,Samsung,M,118.0,VL,381.0,NaN,CONSUMER,Pep Club MTN Base,40.0,13.70,8.99
1859760,Nokia,M,628.0,L,8.0,NaN,CONSUMER,MTN Base,20.0,101.19,42.77
1859813,Samsung,F,349.0,VL,0.0,NaN,CONSUMER,MTNZone,40.0,17.30,17.30
1859924,MOBICEL,F,138.0,VL,0.0,NaN,CONSUMER,Pep Club MTN Base,40.0,19.76,36.02
1860039,Samsung,F,1415.0,VL,10.0,NaN,CONSUMER,MTNZone,20.0,69.67,49.67
1860411,Vodacom,M,0.0,VL,0.0,NaN,CONSUMER,MTN Base,20.0,64.00,44.00
1860447,STYLO,F,939.0,VL,0.0,NaN,CONSUMER,MTNZone,20.0,7.11,27.01
1860544,STYLO,F,1805.0,VL,24.0,NaN,CONSUMER,MTNZone,100.0,37.98,15.98
1860817,Vodacom,F,435.0,VL,141.0,NaN,CONSUMER,MTN Base,20.0,79.00,59.00
1860853,Vodafone,M,1380.0,VL,0.0,NaN,CONSUMER,MTN Base,100.0,11.57,48.57
1860931,Hisense,F,0.0,VL,0.0,NaN,CONSUMER,MTN Base,20.0,67.00,47.00
1861084,Vodafone,M,2681.0,VL,875.0,NaN,CONSUMER,MTNZone,20.0,63.12,33.34
1861104,Nokia,M,775.0,VL,1663.0,NaN,CONSUMER,MTN Base,80.0,29.00,9.00
1861122,ZTE,F,5266.0,VL,0.0,NaN,CONSUMER,MTN Base,80.0,4.58,22.00
1861147,Samsung,F,3134.0,L,73.0,NaN,CONSUMER,MTN Base,60.0,16.43,16.43
1861349,Mobicel,F,430.0,VL,69.0,NaN,CONSUMER,MTNZone,20.0,28.00,48.00
1861439,Vodacom,M,0.0,VL,0.0,NaN,CONSUMER,MTN Base,40.0,42.36,22.36
1861783,MOBICEL,M,806.0,VL,68.0,NaN,CONSUMER,MTN Base,60.0,67.73,14.00
1862359,Samsung,F,1157.0,VL,944.0,NaN,CONSUMER,MTN Base,20.0,69.00,53.00
1862526,MINT,F,5270.0,L,181.0,NaN,CONSUMER,MTN Base,20.0,109.80,65.99
1862599,Samsung,F,2072.0,L,68.0,NaN,CONSUMER,Pep Club MTN Base,40.0,70.00,50.00
1862633,Mobicel,M,1056.0,VL,352.0,NaN,CONSUMER,MTN Base,20.0,19.00,14.00
1862820,Vodafone,F,3373.0,L,566.0,NaN,CONSUMER,MTN Base,40.0,5.46,29.63
1862912,STYLO,F,1526.0,VL,0.0,NaN,CONSUMER,Pep Club MTN Base,20.0,6.25,21.25
1862924,MOBICEL,NaN,876.0,VL,525.0,NaN,CONSUMER,MTN Base,80.0,36.26,16.26
1863243,itel,M,4866.0,VL,0.0,NaN,CONSUMER,MTNZone,60.0,57.58,37.58

In [ ]:
#

In [17]:
corp_data = data.loc[data['LOYALTY_POINTS_REDEEMED']>0]

In [18]:
corp = corp_data.loc[corp_data['CUSTOMER_TYPE'] == 'CORPORATE']

In [19]:
corp['LOYALTY_POINTS_BALANCE'].count()

12

In [20]:
corp[['HS_MAKE','REV_VOICE_ONNET','CONS_TYPE','REV_VOICE_OFFNET','SEX','B2B_TYPE','CUSTOMER_TYPE','TARIFF_TYPE','LOYALTY_POINTS_REDEEMED','SMILE_BALANCE','LOYALTY_POINTS_BALANCE']]

,HS_MAKE,REV_VOICE_ONNET,CONS_TYPE,REV_VOICE_OFFNET,SEX,B2B_TYPE,CUSTOMER_TYPE,TARIFF_TYPE,LOYALTY_POINTS_REDEEMED,SMILE_BALANCE,LOYALTY_POINTS_BALANCE
1558,NaN,0.0,NaN,0.0,M,Consumer-Corporate ...,CORPORATE,PRE,9350.0,111.4500,91.450
4975,NaN,16779.0,NaN,13123.0,NaN,Business-Large ...,CORPORATE,AD5,700.0,27.7900,NaN
5160,NaN,0.0,NaN,0.0,NaN,SME-Medium ...,CORPORATE,C54,100.0,27.8800,NaN
5473,NaN,1330.0,NaN,409.0,NaN,Business-Large ...,CORPORATE,AD5,500.0,30.6000,NaN
5781,NaN,0.0,NaN,0.0,NaN,Business-Medium ...,CORPORATE,C50,600.0,20.5500,NaN
7643,NaN,1201.0,NaN,2274.0,NaN,Business-Dealer ...,CORPORATE,C05,1700.0,28.2193,NaN
8965,NaN,7970.0,NaN,13270.0,NaN,SME-Small ...,CORPORATE,C82,200.0,44.3903,NaN
9452,NaN,0.0,NaN,0.0,NaN,Consumer-Corporate ...,CORPORATE,C02,700.0,44.0870,NaN
9484,NaN,855.0,NaN,0.0,NaN,Business-Medium ...,CORPORATE,C40,1000.0,20.3500,NaN
10108,NaN,44942.0,NaN,54179.0,NaN,Business-Large ...,CORPORATE,C04,1800.0,22.0100,NaN
10826,NaN,0.0,NaN,0.0,NaN,Staff-Permanent ...,CORPORATE,DC2,3150.0,31.0000,NaN
11088,NaN,1849.0,NaN,4335.0,NaN,Business-Large ...,CORPORATE,AD5,500.0,23.5500,NaN
16403,Samsung,0.0,H,0.0,M,Business-Medium ...,CORPORATE,C05,350.0,595.5500,766.550
734779,Apple,0.0,VL,235.0,M,Staff-VIP ...,CORPORATE,DC2,1050.0,431.5200,309.120
795330,Samsung,0.0,VL,0.0,F,Staff-Permanent ...,CORPORATE,DC2,100.0,99.9000,79.900
885773,Vodacom,0.0,VL,0.0,M,Wholesale,CORPORATE,C81,100.0,34.1000,36.140
1392867,SONY,224.0,L,818.0,M,Consumer-Corporate ...,CORPORATE,C82,20.0,451.1940,66.574
1558393,Apple,0.0,VL,1137.0,M,Staff-Permanent ...,CORPORATE,DC1,350.0,154.9000,133.640
1612857,MOBICEL,899.0,VL,0.0,M,Wholesale,CORPORATE,C82,20.0,389.9600,26.670
1658523,Nokia,1352.0,VL,139.0,M,Wholesale,CORPORATE,C18,200.0,132.1300,43.890
1687391,Apple,0.0,VL,188.0,F,Staff-VIP ...,CORPORATE,DC2,100.0,279.0800,247.330
1744547,Samsung,0.0,VL,3.0,F,Staff-VIP ...,CORPORATE,DC2,450.0,51.5300,21.530
1783181,RugGear,0.0,VL,0.0,NaN,Business-VIP ...,CORPORATE,HDI,200.0,120.7000,100.700

In [29]:
#user = data[['HS_MAKE','SEX','B2B_TYPE','CUSTOMER_TYPE','TARIFF_TYPE','LOYALTY_POINTS_REDEEMED','SMILE_BALANCE','LOYALTY_POINTS_BALANCE']]

In [21]:
user = corp.nlargest(5, 'LOYALTY_POINTS_REDEEMED')

In [22]:
user['LOYALTY_POINTS_REDEEMED'].mean()

3410.0

In [23]:
user[['HS_MAKE','SEX','LOYALTY_POINTS_REDEEMED','SMILE_BALANCE','LOYALTY_POINTS_BALANCE','TOT_REV']]

,HS_MAKE,SEX,LOYALTY_POINTS_REDEEMED,SMILE_BALANCE,LOYALTY_POINTS_BALANCE,TOT_REV
1558,NaN,M,9350.0,111.4500,91.45,2168.900000
10826,NaN,NaN,3150.0,31.0000,NaN,0.000000
10108,NaN,NaN,1800.0,22.0100,NaN,-6134.100000
7643,NaN,NaN,1700.0,28.2193,NaN,-22466.400000
734779,Apple,M,1050.0,431.5200,309.12,286.894699

In [24]:
user_1 = cons.nlargest(10, 'LOYALTY_POINTS_BALANCE')

In [25]:
user_1[['HS_MAKE','CONS_TYPE','SEX','B2B_TYPE','CUSTOMER_TYPE','TARIFF_TYPE','LOYALTY_POINTS_REDEEMED','SMILE_BALANCE','LOYALTY_POINTS_BALANCE']]

,HS_MAKE,CONS_TYPE,SEX,B2B_TYPE,CUSTOMER_TYPE,TARIFF_TYPE,LOYALTY_POINTS_REDEEMED,SMILE_BALANCE,LOYALTY_POINTS_BALANCE
812734,Huawei,VL,M,NaN,CONSUMER,UNKNOWN,10100.0,29910.8553,29890.8553
566723,HUAWEI,VL,F,NaN,CONSUMER,MTN Base,900.0,3037.0000,3617.0000
1560804,Apple,VL,F,NaN,CONSUMER,MTN Base,1050.0,1638.0000,3318.0000
481152,Samsung,VL,M,NaN,CONSUMER,MTNZone,300.0,2119.9800,2099.9800
401422,Alcatel,VL,F,NaN,CONSUMER,UNKNOWN,1700.0,1869.8213,1849.8213
1601929,itel,VL,M,NaN,CONSUMER,MTN Base,900.0,1684.0000,1664.0000
1648460,Nokia,VL,F,NaN,CONSUMER,Pep Club MTN Base,1600.0,45.0000,1440.0000
1596352,Alcatel,VL,M,NaN,CONSUMER,MTN Base,700.0,1348.0400,1328.0400
959046,STYLO,VL,M,NaN,CONSUMER,MTN Base,300.0,1312.9900,1292.9900
243629,Samsung,VL,F,NaN,CONSUMER,MTN Base,2150.0,1260.0000,1240.0000

In [26]:
con = data.loc[data['CONS_TYPE']=='H']

In [27]:
con[['HS_MAKE','REV_VOICE_ONNET','REV_VOICE_OFFNET','CONS_TYPE','SEX','B2B_TYPE','CUSTOMER_TYPE','TARIFF_TYPE','LOYALTY_POINTS_REDEEMED','SMILE_BALANCE','LOYALTY_POINTS_BALANCE']]

,HS_MAKE,REV_VOICE_ONNET,REV_VOICE_OFFNET,CONS_TYPE,SEX,B2B_TYPE,CUSTOMER_TYPE,TARIFF_TYPE,LOYALTY_POINTS_REDEEMED,SMILE_BALANCE,LOYALTY_POINTS_BALANCE
8484,Samsung,16418.0,17870.0,H,NaN,Reseller Large ...,CONSUMER,C52,600.0,473.9330,NaN
16403,Samsung,0.0,0.0,H,M,Business-Medium ...,CORPORATE,C05,350.0,595.5500,766.5500
139049,Samsung,0.0,0.0,H,M,NaN,CONSUMER,UNKNOWN,0.0,16914.6200,16894.6200
369384,Samsung,0.0,0.0,H,F,NaN,CONSUMER,UNKNOWN,0.0,17515.6403,17495.6403
538534,Samsung,0.0,0.0,H,M,NaN,CONSUMER,MTN Pay Per Second,0.0,199.2100,170.5400
776183,Samsung,0.0,0.0,H,M,NaN,CONSUMER,UNKNOWN,0.0,5291.4300,5271.4300
803827,Sony,0.0,0.0,H,M,NaN,CONSUMER,MTNZone,0.0,8668.8592,8648.8592
1060627,Samsung,0.0,0.0,H,F,NaN,CONSUMER,UNKNOWN,0.0,799.0500,779.0500
1313479,Apple,0.0,0.0,H,M,NaN,CONSUMER,MTN Pay Per Second,0.0,18.3100,313.3100
1314334,Samsung,0.0,0.0,H,M,NaN,CONSUMER,MTN Pay Per Second,600.0,239.5900,219.5900
1316556,Samsung,0.0,74.0,H,F,NaN,CONSUMER,MTNZone,0.0,1538.8000,1518.8000
1355120,Nokia,1050.0,0.0,H,M,NaN,CONSUMER,MTNZone,900.0,70.4353,15.4953
1480358,Apple,0.0,0.0,H,F,NaN,CONSUMER,MTN Pay Per Second,5300.0,10005.5900,15185.5900
1539615,Nokia,0.0,0.0,H,M,NaN,CONSUMER,MTN Pay Per Second,0.0,287.3400,2892.3400
1642384,Vodacom,70.0,0.0,H,F,NaN,CONSUMER,MTN Pay Per Second,0.0,521.0600,501.0600

In [ ]:
#